# This is a basic workflow to help you get started with Actions

name: closing of the issue

# Controls when the action will run. 
on:
  issues:
    closed:
  
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - id: get-id
      uses: actions/github-script@0.9.0
      with:
        script: |
                            const id = `${{ github.event.issue.body }}`.split('Case number :')[1].split('Opened by :')[0]
                            core.setOutput('id', id)
    - run: echo '${{steps.get-id.outputs.id}}}'
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v1
      env:
        webhook_type: 'json-extended'
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
        data: '{"TicketNumber" :${{steps.get-id.outputs.id}}'
